config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :concerts
  

  root 'welcome#index' #avoir fait la vue/controleur welcom avec "rails g controller welcome index"

end

app/models/concert.rb
class Concert < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:date, :nom, :ville)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_field :ville %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'Back', concerts_path %>

app/views/concerts/index.html.erb
<h1>Listing concerts</h1>

<%# boostrap table %>
<table class="table"> 
  <thead>
    <tr>
      <th>Date</th>
      <th>Nom</th>
      <th>Ville</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.date %></td>
        <td><%= concert.nom %></td>
        <td><%= concert.ville %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Destroy', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concert', new_concert_path, class: 'btn btn-success' %>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= render 'form' %>

<%= link_to 'Back', concerts_path %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @concert.date %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @concert.nom %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @concert.ville %>
</p>

<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'Back', concerts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cuba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  
  <% #bootstrap navbar %>
  <nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li class="active"><a href="<%= root_path %>"> <span class="glyphicon glyphicon-home"></span>   Accueil</a></li>
         <!-- <li class="active"> <span class="glyphicon glyphicon-home"></span> <%= link_to 'Accueil', root_path %>  </li>-->
           
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div> <!-- / .navbar-collapse -->
  </div> <!-- / .container-fluid -->
</nav>
  
<div class="container">
  <%= yield %>
</div>
  
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>